service: linkedin-scraper
provider:
  name: aws
  runtime: python3.9
  region: eu-west-3
  role: arn:aws:iam::545076237434:role/lambda-execution-role

functions:
  scrapJobOffer:
    handler: handler.scrape_job_offer
    timeout: 300
  scrapeJobURLs:
    handler: handler.scrape_job_urls
    timeout: 300
    environment:
      JOB_OFFER_SCRAPER_ARN: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:service}-${sls:stage}-scrapJobOffer
    events:
      - schedule: rate(1 day)

plugins:
  - serverless-python-requirements
